### ISSUE TITLE
Arrays and slices çevirisi

### ISSUE THREAD

**Issue by halilkocaoz** [halilkocaoz/learn-go-with-tests#5]
[Arrays and Slices](https://github.com/halilkocaoz/learn-go-with-tests/blob/turkish/doc-turkish/arrays-and-slices.md)

Çeviriyi yaparken İngilizce bilgisayar bilimi terimlerini veya kod bloklarında olan İngilizce isimlendirmeleri Türkçe'ye çevirmenize gerek yoktur. Veri tipleri, Pointers, Concurency gibi kalıplar veya `Add` olan bir fonksiyon adı İngilizce olduğu gibi kalabilir. 

Şimdiden teşekkürler, bu çeviriyi size atamam için yazmanız yeterli.

**Comment by bariscanyilmaz** [comment]
Bu bölümü çevirebilirim

**Comment by halilkocaoz** [comment]
Çok teşekkürler @bariscanyilmaz, atamayı yaptım.

**Comment by bariscanyilmaz** [comment]
@halilkocaoz kendini atamışsın :D

**Comment by halilkocaoz** [comment]
> @halilkocaoz kendini atamışsın :D

Hahaha. kusura bakma, düzelttim.
